### ISSUE TITLE
Be more precise with provenance.

### ISSUE THREAD

**Issue by dbuenzli** [ocamllabs/2048-tutorial#35]
I also think that we could could be less loose with the possible cases in [`provenance`](https://github.com/ocamllabs/cufp-tutorial/blob/master/2048/src/g2048.ml#L27) by using a variant (see actual comment above the datatype). This could make [this](https://github.com/ocamllabs/cufp-tutorial/blob/master/2048/src/render.ml#L83) pattern match more obvious. It may however complexify the provenance computation code, so this may turn out to be a bad idea.

**Comment by yomimono** [comment]
I had this thought as well when running through the tutorial, and I think it might be less confusing to students to implement it this way.  (Apologies for the thread necromancy.)
