### ISSUE TITLE
Reusing project as teaching material

### ISSUE THREAD

**Issue by tmcgilchrist** [ocamllabs/2048-tutorial#41]
Hi, 
I'm interested in using and possibly adapting this tutorial for use in a workshop I'd like to teach.
Are there any extra restrictions on re-using this repo outside of the BSD2 license placed on the code in the 2048 directory?
The workshop would not be for profit, just fun.

Thanks

**Comment by samoht** [comment]
You are very welcome to do so! Just add a link to that repo so that other people can send their contributions back. Also, if you have some patches to make the tutorial better, we willl accept them gladly :-)

**Comment by samoht** [comment]
Maybe we can try to keep a list of where that tutorial has been used?

**Comment by tmcgilchrist** [comment]
Thanks. I'll be sure to place credit where it's due.

**Comment by yallop** [comment]
> Maybe we can try to keep a list of where that tutorial has been used?

Good idea!  See #42.
